# Change baseurl before deploy
baseurl = "https://tatimun.github.io/apuntatis/"
languageCode = "es-es"
paginate = 5
title = "Apuntatiss ✨🚀"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "es"


hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "tati"
