baseURL = "https://tatimun.github.io/apuntatis/"
languageCode = "es"
title = "Apuntatis"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  term = ["HTML"]
  taxonomy = ["HTML"]

[pagination]
  pagerSize = 10

[params]
  author = "Tati"
  description = "Rompiendo cosas 😋"
  email = "apuntatis@gmail.com"

  # ⭐ RUTAS CORRECTAS PARA GITHUB PAGES
  avatar = "https://tatimun.github.io/apuntatis/images/avatar.gif"
  favicon = "https://tatimun.github.io/apuntatis/images/github-mark.png"
  headerIcon = "https://tatimun.github.io/apuntatis/images/github-mark-white.png"

  twitter = ""
  facebook = ""
  linkedin = ""
  instagram = ""
  tumblr = ""

  location = "Argentina"
  url = "https://tatimun.github.io/apuntatis"
  rss = true
  lastmod = true

  enableSearch = true
  enableGitalk = false

  [[params.links]]
    title = "Mi GitHub"
    href = "https://github.com/tatimun"
    icon = "https://tatimun.github.io/apuntatis/images/github-mark.png"

  [[params.links]]
    title = "Apuntatis"
    href = "https://tatimun.github.io/apuntatis/"
    icon = "https://tatimun.github.io/apuntatis/images/avatar.gif"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
